max_width = 120
tab_spaces = 2
use_small_heuristics = "Max"
edition = "2021"
fn_params_layout = "Tall"
hard_tabs = false
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true
use_try_shorthand = true

